### ISSUE TITLE
Look into how MCLUST calculates BIC

### ISSUE THREAD

**Issue by jalula** [data-edu/tidyLPA#86]
The 'y' axis of  graph produced in the plot_profiles command states 'BIC (smaller is better)', I believe that this is false.  MCLUST calculates BIC as  2×ln(L(theta|x))+k×ln(n) not as −2×ln(L(theta|x))+k×ln(n). In the first case large BICs are better and in the second case small BICs are smaller.  See the following link for more details: 
https://stats.stackexchange.com/questions/237220/mclust-model-selection

**Comment by jrosen48** [comment]
@jalula thank you for your message. I think I remember this from awhile back - I think we take the absolute value of the BIC ([here](https://github.com/jrosen48/tidyLPA/blob/5f68f9e5a5c34a1bf930ed4d5d36fe94fc4278d7/R/compare-solutions.R#L107)) because, I think, it's more commonly calculated the first way (2×ln(L(theta|x))+k×ln(n)). 

Does that check out to you?

**Comment by jalula** [comment]
@jrosen48 thank you for your follow up.  The calculations of BIC check out to me. I am concerned about the labeling of the y axis (line 124) and the interpretation it implies.  In our case a **bigger**  BIC is better than a smaller BIC. The plot is saying the opposite.   To understand this intuitively, ln(L(theta|x)) will be larger if theta is more likely and smaller if theta is less likely.  Does this make sense?

**Comment by cjvanlissa** [comment]
BIC is now correctly calculated (same in Mplus and Mclust)
