### ISSUE TITLE
Calculation of CIs for Means

### ISSUE THREAD

**Issue by MKubsch** [data-edu/tidyLPA#96]
Hi,
I think there are two issues with how you calculate the CIs in plot-profiles.
1) You use ci <- qnorm(.5 * (1 - ci)). I would expect qt(ci, n-1) instead. (n is the number of people in the latent profile)
2) How you calculate you SE in calc_functions. I would expect SE <- SD/sqrt(n) 
As far as I understand your code, you estimate your SD from bootstrapping but never divide by sqrt(n) (n is the number of people in the latent profile). 

If you think I'm mistaken, I would be very interested to hear why you calculate your CIs as you are. 
Thanks

**Comment by cjvanlissa** [comment]
Dear MKubsch,

Can you please explain what you think the problem is?

> 1. ci <- qnorm(.5 * (1 - ci)). I would expect qt(ci, n-1)

I believe it is common practice to use Z for confidence bounds. I'm not sure you can just use "number of people in the latent profile" to calculate a df for the t-distribution, because this does not take classification uncertainty into account. Perhaps I could use posterior class probabilities to approximate the df, but I have not seen this done elsewhere. Are you aware of an example?

> 2\. How you calculate you SE in calc_functions. I would expect SE <- SD/sqrt(n)
>     As far as I understand your code, you estimate your SD from bootstrapping but never divide by sqrt(n) (n is the number of people in the latent profile).

You are describing the standard error of the mean. Every standard error is defined differently. I don't derive the SD by bootstrapping; I derive the standard deviation of the empirical (bootstrapped) sampling distribution, which IS the standard error. https://arxiv.org/pdf/1510.00551.pdf

**Comment by MKubsch** [comment]
Hi, 
Thanks for your clarification! :)

I was originally coming to this issue from tidyLPA 0.2.4 
In plot_profiles in that version, the CI was calculated like this:
ci <- qnorm(0.5 * (1 - ci))
se = ci * (.data$sd/sqrt(.data$n - 1))

To me, that looks pretty much like the standard error of the mean, although I'm a little confused about the n-1 instead of n. 

Given your reply to my original comment, would you consider the above way to calculate a CI as incorrect?

**Comment by cjvanlissa** [comment]
Yes, that is definitely incorrect. As you can see from the reference, bootstrapping is the most appropriate method to derive SEs for mixture models.
